package country

// translate country names to codes and vice versa

//import "fmt"
import "strings"

type CountryInfo struct {
    numcode    int
    alpha2code string
    alpha3code string
    names      []string
}

var countrydata []CountryInfo

func init () {
    countrydata = []CountryInfo{
        {1, "af", "afg", []string{"Afghanistan"}},
        {2, "ax", "ala", []string{"Aland Islands"}},
        {3, "al", "alb", []string{"Albania"}},
        {4, "dz", "dza", []string{"Algeria"}},
        {5, "as", "asm", []string{"American Samoa"}},
        {6, "ad", "and", []string{"Andorra"}},
        {7, "ao", "ago", []string{"Angola"}},
        {8, "ai", "aia", []string{"Anguilla"}},
        {10, "ag", "atg", []string{"Antigua and Barbuda"}},
        {11, "ar", "arg", []string{"Argentina"}},
        {12, "am", "arm", []string{"Armenia"}},
        {13, "aw", "abw", []string{"Aruba"}},
        {14, "au", "aus", []string{"Australia"}},
        {15, "at", "aut", []string{"Austria"}},
        {16, "az", "aze", []string{"Azerbaijan"}},
        {17, "bs", "bhs", []string{"Bahamas", "Bahamas, The", "The Bahamas"}},
        {18, "bh", "bhr", []string{"Bahrain"}},
        {19, "bd", "bgd", []string{"Bangladesh"}},
        {20, "bb", "brb", []string{"Barbados"}},
        {21, "by", "blr", []string{"Belarus"}},
        {22, "be", "bel", []string{"Belgium"}},
        {23, "bz", "blz", []string{"Belize"}},
        {24, "bj", "ben", []string{"Benin"}},
        {25, "bm", "bmu", []string{"Bermuda"}},
        {26, "bt", "btn", []string{"Bhutan"}},
        {27, "bo", "bol", []string{"Bolivia, Plurinational State of", "Bolivia (Plurinational State of)", "Bolivia"}},
        {28, "bq", "bes", []string{"Bonaire, Saint Eustatius and Saba"}},
        {29, "ba", "bih", []string{"Bosnia and Herzegovina"}},
        {30, "bw", "bwa", []string{"Botswana"}},
        {32, "br", "bra", []string{"Brazil"}},
        {34, "bn", "brn", []string{"Brunei Darussalam", "Brunei"}},
        {35, "bg", "bgr", []string{"Bulgaria"}},
        {36, "bf", "bfa", []string{"Burkina Faso"}},
        {37, "bi", "bdi", []string{"Burundi"}},
        {38, "kh", "khm", []string{"Cambodia"}},
        {39, "cm", "cmr", []string{"Cameroon"}},
        {40, "ca", "can", []string{"Canada"}},
        {41, "cv", "cpv", []string{"Cape Verde"}},
        {42, "ky", "cym", []string{"Cayman Islands"}},
        {43, "cf", "caf", []string{"Central African Republic"}},
        {44, "td", "tcd", []string{"Chad"}},
        {45, "cl", "chl", []string{"Chile"}},
        {46, "cn", "chn", []string{"China"}},
        {49, "co", "col", []string{"Colombia"}},
        {50, "km", "com", []string{"Comoros"}},
        {51, "cg", "cog", []string{"Congo", "Congo (Brazzaville)", "Congo, Republic of the", "The Republic of the Congo"}},
        {52, "cd", "cod", []string{"Congo, The Democratic Republic of the", "Democratic Republic of the Congo", "Congo, Democratic Republic of the", "The Democratic Republic of the Congo"}},
        {53, "ck", "cok", []string{"Cook Islands"}},
        {54, "cr", "cri", []string{"Costa Rica"}},
        {55, "ci", "civ", []string{"Cote d'Ivoire"}},
        {56, "hr", "hrv", []string{"Croatia"}},
        {57, "cu", "cub", []string{"Cuba"}},
        {58, "cw", "cuw", []string{"Curacao"}},
        {59, "cy", "cyp", []string{"Cyprus"}},
        {60, "cz", "cze", []string{"Czech Republic"}},
        {61, "dk", "dnk", []string{"Denmark"}},
        {62, "dj", "dji", []string{"Djibouti"}},
        {63, "dm", "dma", []string{"Dominica"}},
        {64, "do", "dom", []string{"Dominican Republic"}},
        {65, "ec", "ecu", []string{"Ecuador"}},
        {66, "eg", "egy", []string{"Egypt"}},
        {67, "sv", "slv", []string{"El Salvador"}},
        {68, "gq", "gnq", []string{"Equatorial Guinea"}},
        {69, "er", "eri", []string{"Eritrea"}},
        {70, "ee", "est", []string{"Estonia"}},
        {71, "et", "eth", []string{"Ethiopia"}},
        {72, "fk", "flk", []string{"Falkland Islands (Malvinas)", "Falkland Islands (Islas Malvinas)"}},
        {73, "fo", "fro", []string{"Faroe Islands", "Faeroe Islands"}},
        {74, "fj", "fji", []string{"Fiji"}},
        {75, "fi", "fin", []string{"Finland"}},
        {76, "fr", "fra", []string{"France"}},
        {77, "gf", "guf", []string{"French Guiana"}},
        {78, "pf", "pyf", []string{"French Polynesia"}},
        {80, "ga", "gab", []string{"Gabon"}},
        {81, "gm", "gmb", []string{"Gambia", "Gambia, The"}},
        {82, "ge", "geo", []string{"Georgia"}},
        {83, "de", "deu", []string{"Germany"}},
        {84, "gh", "gha", []string{"Ghana"}},
        {85, "gi", "gib", []string{"Gibraltar"}},
        {86, "gr", "grc", []string{"Greece"}},
        {87, "gl", "grl", []string{"Greenland"}},
        {88, "gd", "grd", []string{"Grenada"}},
        {89, "gp", "glp", []string{"Guadeloupe"}},
        {90, "gu", "gum", []string{"Guam"}},
        {91, "gt", "gtm", []string{"Guatemala"}},
        {92, "gg", "ggy", []string{"Guernsey"}},
        {93, "gn", "gin", []string{"Guinea"}},
        {94, "gw", "gnb", []string{"Guinea-Bissau"}},
        {95, "gy", "guy", []string{"Guyana"}},
        {96, "ht", "hti", []string{"Haiti"}},
        {98, "va", "vat", []string{"Holy See (Vatican City State)", "Holy See", "Vatican City", "Holy See (Vatican City)"}},
        {99, "hn", "hnd", []string{"Honduras"}},
        {100, "hk", "hkg", []string{"Hong Kong", "China, Hong Kong Special Administrative Region", "Hong Kong S.A.R.", "Hong Kong Special Administrative Region of China"}},
        {101, "hu", "hun", []string{"Hungary"}},
        {102, "is", "isl", []string{"Iceland"}},
        {103, "in", "ind", []string{"India"}},
        {104, "id", "idn", []string{"Indonesia"}},
        {105, "ir", "irn", []string{"Iran, Islamic Republic of", "Iran (Islamic Republic of)", "Iran"}},
        {106, "iq", "irq", []string{"Iraq"}},
        {107, "ie", "irl", []string{"Ireland"}},
        {108, "im", "imn", []string{"Isle of Man"}},
        {109, "il", "isr", []string{"Israel"}},
        {110, "it", "ita", []string{"Italy"}},
        {111, "jm", "jam", []string{"Jamaica"}},
        {112, "jp", "jpn", []string{"Japan"}},
        {113, "je", "jey", []string{"Jersey"}},
        {114, "jo", "jor", []string{"Jordan"}},
        {115, "kz", "kaz", []string{"Kazakhstan", "Kazakstan"}},
        {116, "ke", "ken", []string{"Kenya"}},
        {117, "ki", "kir", []string{"Kiribati"}},
        {118, "kp", "prk", []string{"Korea, Democratic People's Republic of", "Democratic People's Republic of Korea", "North Korea"}},
        {119, "kr", "kor", []string{"Korea, Republic of", "Republic of Korea", "South Korea"}},
        {120, "kw", "kwt", []string{"Kuwait"}},
        {121, "kg", "kgz", []string{"Kyrgyzstan"}},
        {122, "la", "lao", []string{"Lao People's Democratic Republic"}},
        {123, "lv", "lva", []string{"Latvia"}},
        {124, "lb", "lbn", []string{"Lebanon"}},
        {125, "ls", "lso", []string{"Lesotho"}},
        {126, "lr", "lbr", []string{"Liberia"}},
        {127, "ly", "lby", []string{"Libya"}},
        {128, "li", "lie", []string{"Liechtenstein"}},
        {129, "lt", "ltu", []string{"Lithuania"}},
        {130, "lu", "lux", []string{"Luxembourg"}},
        {131, "mo", "mac", []string{"Macao", "China, Macao Special Administrative Region", "Macau", "Macau S.A.R", "Macau S.A.R.", "Macao Special Administrative Region of China"}},
        {132, "mk", "mkd", []string{"Macedonia, The Former Yugoslav Republic of", "The former Yugoslav Republic of Macedonia", "Macedonia", "Macedonia, Former Yugoslav Republic of"}},
        {133, "mg", "mdg", []string{"Madagascar"}},
        {134, "mw", "mwi", []string{"Malawi"}},
        {135, "my", "mys", []string{"Malaysia"}},
        {136, "mv", "mdv", []string{"Maldives"}},
        {137, "ml", "mli", []string{"Mali"}},
        {138, "mt", "mlt", []string{"Malta"}},
        {139, "mh", "mhl", []string{"Marshall Islands"}},
        {140, "mq", "mtq", []string{"Martinique"}},
        {141, "mr", "mrt", []string{"Mauritania"}},
        {142, "mu", "mus", []string{"Mauritius"}},
        {143, "yt", "myt", []string{"Mayotte"}},
        {144, "mx", "mex", []string{"Mexico"}},
        {145, "fm", "fsm", []string{"Micronesia, Federated States of", "Micronesia (Federated States of)", "Federated States of Micronesia"}},
        {146, "md", "mda", []string{"Moldova, Republic of", "Republic of Moldova"}},
        {147, "mc", "mco", []string{"Monaco"}},
        {148, "mn", "mng", []string{"Mongolia"}},
        {149, "me", "mne", []string{"Montenegro"}},
        {150, "ms", "msr", []string{"Montserrat"}},
        {151, "ma", "mar", []string{"Morocco"}},
        {152, "mz", "moz", []string{"Mozambique"}},
        {153, "mm", "mmr", []string{"Myanmar", "Burma"}},
        {154, "na", "nam", []string{"Namibia"}},
        {155, "nr", "nru", []string{"Nauru"}},
        {156, "np", "npl", []string{"Nepal"}},
        {157, "nl", "nld", []string{"Netherlands"}},
        {158, "nc", "ncl", []string{"New Caledonia"}},
        {159, "nz", "nzl", []string{"New Zealand"}},
        {160, "ni", "nic", []string{"Nicaragua"}},
        {161, "ne", "ner", []string{"Niger"}},
        {162, "ng", "nga", []string{"Nigeria"}},
        {163, "nu", "niu", []string{"Niue"}},
        {164, "nf", "nfk", []string{"Norfolk Island"}},
        {165, "mp", "mnp", []string{"Northern Mariana Islands"}},
        {166, "no", "nor", []string{"Norway"}},
        {167, "om", "omn", []string{"Oman"}},
        {168, "pk", "pak", []string{"Pakistan"}},
        {169, "pw", "plw", []string{"Palau"}},
        {170, "ps", "pse", []string{"Palestine, State of", "State of Palestine"}},
        {171, "pa", "pan", []string{"Panama"}},
        {172, "pg", "png", []string{"Papua New Guinea"}},
        {173, "py", "pry", []string{"Paraguay"}},
        {174, "pe", "per", []string{"Peru"}},
        {175, "ph", "phl", []string{"Philippines"}},
        {176, "pn", "pcn", []string{"Pitcairn", "Pitcairn Islands", "Pitcairn Island"}},
        {177, "pl", "pol", []string{"Poland"}},
        {178, "pt", "prt", []string{"Portugal"}},
        {179, "pr", "pri", []string{"Puerto Rico"}},
        {180, "qa", "qat", []string{"Qatar"}},
        {181, "re", "reu", []string{"Reunion"}},
        {182, "ro", "rou", []string{"Romania"}},
        {183, "ru", "rus", []string{"Russian Federation"}},
        {184, "rw", "rwa", []string{"Rwanda"}},
        {185, "bl", "blm", []string{"Saint Barthelemy", "Saint-Barthelemy"}},
        {186, "sh", "shn", []string{"Saint Helena, Ascension and Tristan da Cunha", "Saint Helena"}},
        {187, "kn", "kna", []string{"Saint Kitts and Nevis"}},
        {188, "lc", "lca", []string{"Saint Lucia"}},
        {189, "mf", "maf", []string{"Saint Martin (French part)", "Saint-Martin (French part)", "Saint Martin", "Saint-Martin"}},
        {190, "pm", "spm", []string{"Saint Pierre and Miquelon"}},
        {191, "vc", "vct", []string{"Saint Vincent and the Grenadines"}},
        {192, "ws", "wsm", []string{"Samoa"}},
        {193, "sm", "smr", []string{"San Marino"}},
        {194, "st", "stp", []string{"Sao Tome and Principe"}},
        {195, "sa", "sau", []string{"Saudi Arabia"}},
        {196, "sn", "sen", []string{"Senegal"}},
        {197, "rs", "srb", []string{"Serbia"}},
        {198, "sc", "syc", []string{"Seychelles"}},
        {199, "sl", "sle", []string{"Sierra Leone"}},
        {200, "sg", "sgp", []string{"Singapore"}},
        {201, "sx", "sxm", []string{"Sint Maarten (Dutch part)"}},
        {202, "sk", "svk", []string{"Slovakia"}},
        {203, "si", "svn", []string{"Slovenia"}},
        {204, "sb", "slb", []string{"Solomon Islands"}},
        {205, "so", "som", []string{"Somalia"}},
        {206, "za", "zaf", []string{"South Africa"}},
        {208, "ss", "ssd", []string{"South Sudan"}},
        {209, "es", "esp", []string{"Spain"}},
        {210, "lk", "lka", []string{"Sri Lanka"}},
        {211, "sd", "sdn", []string{"Sudan"}},
        {212, "sr", "sur", []string{"Suriname"}},
        {213, "sj", "sjm", []string{"Svalbard and Jan Mayen", "Svalbard and Jan Mayen Islands"}},
        {214, "sz", "swz", []string{"Swaziland"}},
        {215, "se", "swe", []string{"Sweden"}},
        {216, "ch", "che", []string{"Switzerland"}},
        {217, "sy", "syr", []string{"Syrian Arab Republic", "Syria", "Golan Heights (Israeli-occupied)"}},
        {219, "tj", "tjk", []string{"Tajikistan"}},
        {220, "tz", "tza", []string{"Tanzania, United Republic of", "United Republic of Tanzania"}},
        {221, "th", "tha", []string{"Thailand"}},
        {222, "tl", "tls", []string{"Timor-Leste", "East Timor"}},
        {223, "tg", "tgo", []string{"Togo"}},
        {224, "tk", "tkl", []string{"Tokelau"}},
        {225, "to", "ton", []string{"Tonga"}},
        {226, "tt", "tto", []string{"Trinidad and Tobago"}},
        {227, "tn", "tun", []string{"Tunisia"}},
        {228, "tr", "tur", []string{"Turkey"}},
        {229, "tm", "tkm", []string{"Turkmenistan"}},
        {230, "tc", "tca", []string{"Turks and Caicos Islands"}},
        {231, "tv", "tuv", []string{"Tuvalu"}},
        {232, "ug", "uga", []string{"Uganda"}},
        {233, "ua", "ukr", []string{"Ukraine"}},
        {234, "ae", "are", []string{"United Arab Emirates"}},
        {235, "gb", "gbr", []string{"United Kingdom", "United Kingdom of Great Britain and Northern Ireland", "Great Britain", "UK"}},
        {236, "us", "usa", []string{"United States", "United States of America", "US", "USA"}},
        {238, "uy", "ury", []string{"Uruguay"}},
        {239, "uz", "uzb", []string{"Uzbekistan"}},
        {240, "vu", "vut", []string{"Vanuatu"}},
        {241, "ve", "ven", []string{"Venezuela, Bolivarian Republic of", "Venezuela (Bolivarian Republic of)", "Venezuela"}},
        {242, "vn", "vnm", []string{"Viet Nam", "Vietnam"}},
        {243, "vg", "vgb", []string{"Virgin Islands, British", "British Virgin Islands", "Virgin Islands (UK)"}},
        {244, "vi", "vir", []string{"Virgin Islands, U.S.", "United States Virgin Islands", "Virgin Islands (US)", "Virgin Islands"}},
        {245, "wf", "wlf", []string{"Wallis and Futuna", "Wallis and Futuna Islands"}},
        {246, "eh", "esh", []string{"Western Sahara"}},
        {247, "ye", "yem", []string{"Yemen"}},
        {248, "zm", "zmb", []string{"Zambia"}},
        {249, "zw", "zwe", []string{"Zimbabwe"}},
    }
}

func Code2country(country string) string {
    for c := range countrydata {
        if (countrydata[c].alpha3code == country) {
            return countrydata[c].names[0]
        }
    }
    return ""
}
            

func Country2code(country string) string {
    for c := range countrydata {
        for n := range countrydata[c].names {
            if (strings.EqualFold(countrydata[c].names[n], country)) {
                return countrydata[c].alpha3code
            }
        }
    }
    return ""
}

/*
func main () {
//    fmt.Printf("%q\n", countrydata)
    fmt.Printf("%s => %s\n", os.Args[1], Country2code(os.Args[1]))
}
*/
